-- Support for  Schallfalke's Schall Transport Group mod
local subgroup_shipequip = "water_transport"

if mods["SchallTransportGroup"] then
	subgroup_shipequip = "water_equipment"
end

        data:extend({
        {      
        type = "item", 
        name = "bridge_base", 
        icon = "__cargo-ships__/graphics/icons/bridge.png", 
        icon_size = 128,
        subgroup = subgroup_shipequip,
        flags = {},
        order = "a[water-system]-e[bridge_base]",
        place_result = "bridge_base", 
        stack_size = 5, 
        },
        { 
        type = "item", 
        name = "bridge_north", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_north", 
        stack_size = 5, 
        },
        {      
        type = "item", 
        name = "bridge_north_closed", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_north_closed", 
        stack_size = 5, 
        },
        {
        type = "item", 
        name = "bridge_east", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_east", 
        stack_size = 5, 
        },
        {      
        type = "item", 
        name = "bridge_east_closed", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_east_closed", 
        stack_size = 5, 
        },
        {      
        type = "item", 
        name = "bridge_south", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_south", 
        stack_size = 5, 
        },
        {      
        type = "item", 
        name = "bridge_south_closed", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_south_closed", 
        stack_size = 5, 
        },
       {
        type = "item", 
        name = "bridge_west", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_west", 
        stack_size = 5, 
        },
        {      
        type = "item", 
        name = "bridge_west_closed", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_west_closed", 
        stack_size = 5, 
        },
        {
        type = "item", 
        name = "invisible_rail", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "invisible_rail", 
        stack_size = 5, 
        },
        {
        type = "item", 
        name = "bridge_crossing", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_crossing", 
        stack_size = 5, 
        },
        { 
        type = "item", 
        name = "invisible_chain_signal", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "invisible_chain_signal", 
        stack_size = 5, 
        },

        { 
        type = "item", 
        name = "bridge_north_clickable", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_north_clickable", 
        stack_size = 5, 
        },
        { 
        type = "item", 
        name = "bridge_east_clickable", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_east_clickable", 
        stack_size = 5, 
        },
        { 
        type = "item", 
        name = "bridge_south_clickable", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_south_clickable", 
        stack_size = 5, 
        },
        { 
        type = "item", 
        name = "bridge_west_clickable", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_west_clickable", 
        stack_size = 5, 
        },
        { 
        type = "item", 
        name = "bridge_north_open", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_north_open", 
        stack_size = 5, 
        },
        { 
        type = "item", 
        name = "bridge_east_open", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_east_open", 
        stack_size = 5, 
        },
        { 
        type = "item", 
        name = "bridge_south_open", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_south_open", 
        stack_size = 5, 
        },
        { 
        type = "item", 
        name = "bridge_west_open", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = subgroup_shipequip,
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_west_open", 
        stack_size = 5, 
        },
        
})










