        data:extend({
        {      
        type = "item", 
        name = "bridge_base", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = "water_transport",
        flags = {},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_base", 
        stack_size = 5, 
        },
        { 
        type = "item", 
        name = "bridge_north", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = "water_transport",
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_north", 
        stack_size = 5, 
        },
        {      
        type = "item", 
        name = "bridge_north_closed", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = "water_transport",
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_north_closed", 
        stack_size = 5, 
        },
        {
        type = "item", 
        name = "bridge_east", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = "water_transport",
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_east", 
        stack_size = 5, 
        },
        {      
        type = "item", 
        name = "bridge_east_closed", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = "water_transport",
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_east_closed", 
        stack_size = 5, 
        },
        {      
        type = "item", 
        name = "bridge_south", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = "water_transport",
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_south", 
        stack_size = 5, 
        },
        {      
        type = "item", 
        name = "bridge_south_closed", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = "water_transport",
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_south_closed", 
        stack_size = 5, 
        },
       {
        type = "item", 
        name = "bridge_west", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = "water_transport",
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_west", 
        stack_size = 5, 
        },
        {      
        type = "item", 
        name = "bridge_west_closed", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = "water_transport",
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_west_closed", 
        stack_size = 5, 
        },
        {
        type = "item", 
        name = "invisible_rail", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = "water_transport",
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "invisible_rail", 
        stack_size = 5, 
        },
        {
        type = "item", 
        name = "bridge_crossing", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = "water_transport",
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "bridge_crossing", 
        stack_size = 5, 
        },
        { 
        type = "item", 
        name = "invisible_cahin_signal", 
        icon = "__cargo-ships__/graphics/blank.png", 
        icon_size = 2,
        subgroup = "water_transport",
        flags = {"hidden"},
        order = "b[fluids]-c[oil_rig]",
        place_result = "invisible_chain_signal", 
        stack_size = 5, 
        },
        
})










