-- Support for  Schallfalke's Schall Transport Group mod
local subgroup_shipequip = "water_transport"

if mods["SchallTransportGroup"] then
	subgroup_shipequip = "water_equipment"
end

data:extend({
  {
    type = "item",
    name = "bridge_base",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {},
    order = "a[water-system]-e[bridge_base]",
    place_result = "bridge_base",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_north",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_north",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_north_closed",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_north_closed",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_east",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_east",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_east_closed",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_east_closed",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_south",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_south",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_south_closed",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_south_closed",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_west",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_west",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_west_closed",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_west_closed",
    stack_size = 5,
  },
  {
    type = "item",
    name = "invisible_rail",
    icon = "__base__/graphics/icons/rail.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "invisible_rail",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_crossing",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_crossing",
    stack_size = 5,
  },
  {
    type = "item",
    name = "invisible_chain_signal",
    icon = GRAPHICSPATH .. "icons/chain_buoy.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "invisible_chain_signal",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_north_clickable",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_north_clickable",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_east_clickable",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_east_clickable",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_south_clickable",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_south_clickable",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_west_clickable",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_west_clickable",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_north_open",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_north_open",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_east_open",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_east_open",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_south_open",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_south_open",
    stack_size = 5,
  },
  {
    type = "item",
    name = "bridge_west_open",
    icon = GRAPHICSPATH .. "icons/bridge.png",
    icon_size = 64,
    subgroup = subgroup_shipequip,
    flags = {"hidden"},
    order = "b[fluids]-c[oil_rig]",
    place_result = "bridge_west_open",
    stack_size = 5,
  },

})










