require("__cargo-ships__/prototypes/water_rails")
require("__cargo-ships__/prototypes/buoys")
require("__cargo-ships__/prototypes/ships")
require("__cargo-ships__/prototypes/ship_pump")
require("__cargo-ships__/prototypes/oil_rig")
require("__cargo-ships__/prototypes/bridge")
--require("__cargo-ships__/prototypes/crane")
